[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/BoschSensortec/Bosch-BME68x-Library
    https://github.com/boschsensortec/Bosch-BSEC2-Library.git#Firmware_update_2.1.5
    ; https://github.com/boschsensortec/Bosch-BSEC2-Library.git
    ; https://github.com/BoschSensortec/BME68x-Sensor-API.git
    ArduinoJson@6.19.4
    RTClib@2.0.3
    SdFat@2.1.2
    ; Bosch_BSEC2_Library
    Wire
; build_flags =
;   -I lib/bme68x/include    ls /dev/